# Compatibility with Hopper GPUs like H200
ARG COMPUTE_CAPABILITY=90
ARG CUDA_VERSION=12.8.0
ARG IMAGE_DISTRO=ubi9

FROM nvidia/cuda:${CUDA_VERSION}-devel-${IMAGE_DISTRO} AS builder

ARG COMPUTE_CAPABILITY
ARG CUDA_VERSION
ARG IMAGE_DISTRO

RUN dnf -y install make gcc-c++

WORKDIR /build

COPY . /build/

ENV COMPUTE_CAPABILITY=${COMPUTE_CAPABILITY}
ENV CUDA_VERSION=${CUDA_VERSION}
ENV IMAGE_DISTRO=${IMAGE_DISTRO}

RUN make clean && make COMPUTE_CAPABILITY=$COMPUTE_CAPABILITY CUDA_VERSION=$CUDA_VERSION IMAGE_DISTRO=$IMAGE_DISTRO

FROM nvidia/cuda:${CUDA_VERSION}-runtime-${IMAGE_DISTRO}

COPY --from=builder /build/gpu_burn /app/
COPY --from=builder /build/compare.ptx /app/

WORKDIR /app

ENTRYPOINT ["./gpu_burn"]
CMD ["60"]
